instant-item-pickup-radius: 2.0
disable-thunder-fire: true
crop-auto-plant: true
beacon-mob-grief-protection: true
wandering-trader-rare-trade: true
timber-tree: true
open-shulker-as-item: true
pet-owner: true
hotbar-reload: true
